param(
  [string]$Configuration = "Release",
  [string]$STS2GameDir = "D:\Steam\steamapps\common\Slay the Spire 2"
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$project = Join-Path $repoRoot "src\GongdouSts2FrierenMod\GongdouSts2FrierenMod.csproj"
$dotnet = "C:\Program Files\dotnet\dotnet.exe"
if (-not (Test-Path -LiteralPath $dotnet)) {
  $dotnet = "dotnet"
}

& $dotnet build $project -c $Configuration -p:STS2GameDir="$STS2GameDir"

$sourceDir = Join-Path $repoRoot "src\GongdouSts2FrierenMod\bin\$Configuration\net9.0"
$assetRoot = @(Get-ChildItem -LiteralPath (Join-Path $repoRoot "docs") -Directory |
  Where-Object { $_.Name -like "*800*" -and $_.Name -like "*20260527" } |
  Select-Object -First 1 -ExpandProperty FullName)[0]
$modsRoot = Join-Path $STS2GameDir "mods"
$legacyModDir = Join-Path $modsRoot "Gongdou_STS2_Frieren_Character"
foreach ($dir in @($modsRoot, $legacyModDir)) {
  if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir | Out-Null
  }
}

$frierenManifest = Get-Content -LiteralPath (Join-Path $sourceDir "mod_manifest.json") -Raw | ConvertFrom-Json

function Write-DummyModManifest([string]$Path, [string]$Id, [string]$Name) {
  $manifest = [ordered]@{
    id = $Id
    name = $Name
    author = "x1a0reN"
    description = "Compatibility marker generated by GongDou installer."
    version = $frierenManifest.version
    has_pck = $false
    has_dll = $false
    affects_gameplay = $false
  }
  $json = $manifest | ConvertTo-Json -Depth 4
  Set-Content -LiteralPath $Path -Value $json -Encoding UTF8
}

function Disable-LegacyAssetJsonManifests([string]$AssetPath) {
  if (-not (Test-Path -LiteralPath $AssetPath)) {
    return
  }

  $root = [System.IO.Path]::GetFullPath($AssetPath).TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
  Get-ChildItem -LiteralPath $AssetPath -Recurse -File -Filter "*.json" | ForEach-Object {
    $file = [System.IO.Path]::GetFullPath($_.FullName)
    if (-not $file.StartsWith($root, [System.StringComparison]::OrdinalIgnoreCase)) {
      throw "Refusing to disable JSON outside Frieren asset root: $file"
    }

    $target = "$file.gongdou-disabled"
    $index = 1
    while (Test-Path -LiteralPath $target) {
      $target = "$file.gongdou-disabled-$index"
      $index += 1
    }

    Rename-Item -LiteralPath $file -NewName ([System.IO.Path]::GetFileName($target)) -Force
  }
}

Copy-Item -LiteralPath (Join-Path $sourceDir "GongdouSts2FrierenMod.dll") -Destination (Join-Path $modsRoot "Gongdou_STS2_Frieren_Character.dll") -Force
Copy-Item -LiteralPath (Join-Path $sourceDir "GongdouSts2FrierenMod.dll") -Destination (Join-Path $modsRoot "GongdouSts2FrierenMod.dll") -Force
Write-DummyModManifest (Join-Path $modsRoot "Gongdou_STS2_Frieren_Character.json") "Gongdou_STS2_Frieren_Character_CompatMarker" "GongDou STS2 Frieren Character Compat Marker"
Copy-Item -LiteralPath (Join-Path $sourceDir "GongdouSts2FrierenMod.dll") -Destination (Join-Path $legacyModDir "Gongdou_STS2_Frieren_Character.dll") -Force
Copy-Item -LiteralPath (Join-Path $sourceDir "GongdouSts2FrierenMod.dll") -Destination (Join-Path $legacyModDir "GongdouSts2FrierenMod.dll") -Force
Copy-Item -LiteralPath (Join-Path $sourceDir "mod_manifest.json") -Destination (Join-Path $legacyModDir "mod_manifest.json") -Force

function Copy-FrierenAssetDir([int]$ExpectedPngCount, [string]$TargetName) {
  $sourcePath = @(Get-ChildItem -LiteralPath $assetRoot -Directory | Where-Object {
    @(Get-ChildItem -LiteralPath $_.FullName -Recurse -File -Filter "*.png").Count -eq $ExpectedPngCount
  } | Select-Object -First 1 -ExpandProperty FullName)[0]

  if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Frieren asset source missing: $sourcePath"
  }

  $targetPath = Join-Path (Join-Path $modsRoot "assets\frieren") $TargetName
  if (-not (Test-Path -LiteralPath $targetPath)) {
    New-Item -ItemType Directory -Path $targetPath -Force | Out-Null
  }

  Copy-Item -Path (Join-Path $sourcePath "*") -Destination $targetPath -Recurse -Force
}

function Copy-FrierenCharacterAsset([string]$SourcePath, [string]$TargetName) {
  $sourcePath = $SourcePath
  if (-not (Test-Path -LiteralPath $sourcePath)) {
    throw "Frieren character asset missing: $sourcePath"
  }

  $targetPaths = @(
    (Join-Path $modsRoot "assets\frieren\character"),
    (Join-Path $legacyModDir "assets\frieren\character")
  )

  foreach ($targetPath in $targetPaths) {
    if (-not (Test-Path -LiteralPath $targetPath)) {
      New-Item -ItemType Directory -Path $targetPath -Force | Out-Null
    }

    Copy-Item -LiteralPath $sourcePath -Destination (Join-Path $targetPath $TargetName) -Force
  }
}

Copy-FrierenAssetDir 91 "cards"
Copy-FrierenAssetDir 10 "relics"
Copy-FrierenAssetDir 5 "potions"
Add-Type -AssemblyName System.Drawing
$rootPngs = @(Get-ChildItem -LiteralPath $assetRoot -File -Filter "*.png" | ForEach-Object {
  $image = [System.Drawing.Image]::FromFile($_.FullName)
  try {
    [pscustomobject]@{
      FullName = $_.FullName
      Length = $_.Length
      Width = $image.Width
      Height = $image.Height
    }
  }
  finally {
    $image.Dispose()
  }
})
$modelFile = @($rootPngs |
  Where-Object { $_.Width -le 1000 -and $_.Height -le 1000 } |
  Sort-Object Length -Descending |
  Select-Object -First 1)[0]
$coverFile = @($rootPngs |
  Where-Object { $_.Width -ge 1600 -and $_.Height -ge 900 } |
  Sort-Object Length -Descending |
  Select-Object -First 1)[0]
if ($null -eq $modelFile -or $null -eq $coverFile) {
  throw "Expected Frieren character model and cover images under: $assetRoot"
}
Copy-FrierenCharacterAsset $modelFile.FullName "model.png"
Copy-FrierenCharacterAsset $coverFile.FullName "cover.png"
Disable-LegacyAssetJsonManifests (Join-Path $modsRoot "assets\frieren")
Disable-LegacyAssetJsonManifests (Join-Path $legacyModDir "assets\frieren")

Write-Host "Installed Frieren character mod to $modsRoot and $legacyModDir"
